name: CI

on:
  push:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: ./.
      with:
        token: ${{ secrets.ACCESS_TOEKN_AUTO_MERGE_DEPENDABOT_PR_BOT }}
